services:
  cashing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ref
    environment:
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      NOMINATIM_USER_AGENT: ${NOMINATIM_USER_AGENT}
    stdin_open: true
    tty: true
    restart: always
